In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os
import sklearn

In [3]:
train_data = pd.read_csv('train_assignment.csv')
train_data

,id,marital_status_code,application_mode_code,application_order,course_code,attendance_shift_code,previous_qualification_code,previous_qualification_grade,nationality_code,mother_qualification_code,...,cu2_credited,cu2_enrolled,cu2_evaluations,cu2_approved,cu2_grade,cu2_without_evaluations,unemployment_rate,inflation_rate,gdp,Target
0,100001,1,1,2,9500,1,1,133.0,1,1,...,0,8,8,7,13.428571,0,12.7,3.7,-1.70,Graduate
1,100002,4,39,1,9853,1,12,133.1,1,34,...,0,6,7,0,0.000000,0,7.6,2.6,0.32,Dropout
2,100003,1,17,3,9773,1,1,133.0,1,38,...,0,6,11,4,12.500000,0,9.4,-0.8,-3.12,Enrolled
3,100004,1,1,2,171,1,1,133.1,1,37,...,0,0,0,0,0.000000,0,7.6,2.6,0.32,Dropout
4,100005,1,1,1,9238,1,1,124.0,1,1,...,0,6,6,6,11.500000,0,16.2,0.3,-0.92,Enrolled
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76513,176514,1,17,1,9500,1,1,126.0,1,38,...,0,8,9,8,13.750000,0,16.2,0.3,-0.92,Graduate
76514,176515,1,1,1,9147,1,1,130.0,1,1,...,0,5,10,4,12.000000,0,16.2,0.3,-0.92,Graduate
76515,176516,1,15,1,9130,1,1,150.0,1,2,...,0,6,11,5,12.857143,0,13.9,-0.3,0.79,Graduate
76516,176517,1,39,1,8014,0,1,133.1,1,37,...,0,6,6,6,13.333333,0,15.5,2.8,-4.06,Graduate
76517,176518,1,18,1,9147,1,1,160.0,1,19,...,0,5,9,4,13.400000,0,10.8,1.4,1.74,Graduate

In [6]:
from pathlib import Path
import importlib
import eda_train_data

importlib.reload(eda_train_data)

summary = eda_train_data.run_eda(
    train_data,
    output_dir="eda_output",
    target_col="Target",
    id_col="id",
    max_categorical_levels=20,
    max_grid_columns=12,
    input_label="train_assignment.csv",
)

print("EDA completed. Artifacts saved under:", summary["output_dir"])
print("Rows:", summary["rows"], "| Columns:", summary["columns"], "| Target:", summary["target_column"])

tables_dir = Path(summary["tables_dir"])
display(pd.read_csv(tables_dir / "column_profile.csv").head(10))
display(pd.read_csv(tables_dir / "missingness.csv").head(10))
display(pd.read_csv(tables_dir / "numeric_summary.csv").head(10))

EDA completed. Artifacts saved under: eda_output
Rows: 76518 | Columns: 38 | Target: Target

                         column    dtype  n_unique  missing_count  missing_pct
0                            id    int64     76518              0          0.0
1           marital_status_code    int64         6              0          0.0
2         application_mode_code    int64        22              0          0.0
3             application_order    int64         8              0          0.0
4                   course_code    int64        19              0          0.0
5         attendance_shift_code    int64         2              0          0.0
6   previous_qualification_code    int64        21              0          0.0
7  previous_qualification_grade  float64       110              0          0.0
8              nationality_code    int64        18              0          0.0
9     mother_qualification_code    int64        35              0          0.0

                    column  missing_pct  missing_count
0                       id          0.0              0
1             cu2_credited          0.0              0
2       international_flag          0.0              0
3             cu1_credited          0.0              0
4             cu1_enrolled          0.0              0
5          cu1_evaluations          0.0              0
6             cu1_approved          0.0              0
7                cu1_grade          0.0              0
8  cu1_without_evaluations          0.0              0
9             cu2_enrolled          0.0              0

,column,count,mean,std,min,1%,5%,25%,50%,75%,95%,99%,max,missing_pct,zero_pct,skew,kurtosis
0,id,76518.0,138259.500000,22088.988286,100001.0,100766.17,103826.85,119130.25,138259.5,157388.75,172692.15,175752.83,176518.0,0.0,0.000000,0.000000,-1.200000
1,marital_status_code,76518.0,1.111934,0.441669,1.0,1.00,1.00,1.00,1.0,1.00,2.00,4.00,6.0,0.0,0.000000,5.382852,34.866324
2,application_mode_code,76518.0,16.054419,16.682337,1.0,1.00,1.00,1.00,17.0,39.00,43.00,44.00,53.0,0.0,0.000000,0.596232,-1.241859
3,application_order,76518.0,1.644410,1.229645,0.0,1.00,1.00,1.00,1.0,2.00,5.00,6.00,9.0,0.0,0.003921,2.043582,3.393705
4,course_code,76518.0,9001.286377,1803.438531,33.0,171.00,8014.00,9119.00,9254.0,9670.00,9991.00,9991.00,9991.0,0.0,0.000000,-4.481016,19.081583
5,attendance_shift_code,76518.0,0.915314,0.278416,0.0,0.00,0.00,1.00,1.0,1.00,1.00,1.00,1.0,0.0,8.468596,-2.983488,6.901384
6,previous_qualification_code,76518.0,3.658760,8.623774,1.0,1.00,1.00,1.00,1.0,1.00,19.00,39.00,43.0,0.0,0.000000,3.436245,10.793372
7,previous_qualification_grade,76518.0,132.378766,10.995328,95.0,102.00,115.00,125.00,133.1,140.00,150.00,160.00,190.0,0.0,0.000000,0.221560,1.164759
8,nationality_code,76518.0,1.226600,3.392183,1.0,1.00,1.00,1.00,1.0,1.00,1.00,1.00,109.0,0.0,0.000000,20.074583,493.320689
9,mother_qualification_code,76518.0,19.837633,15.399456,1.0,1.00,1.00,1.00,19.0,37.00,38.00,38.00,44.0,0.0,0.000000,-0.045535,-1.646693

## Train Model and Generate submission.csv
Train a multiclass classifier for `Target` and create `submission.csv` with `id` and `Target` for `test_assignment.csv`.

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, f1_score, accuracy_score
from sklearn.utils.class_weight import compute_class_weight
import numpy as np
import pandas as pd

train_df = pd.read_csv("train_assignment.csv")
test_df = pd.read_csv("test_assignment.csv")

feature_cols = [c for c in train_df.columns if c not in ["Target", "id"]]
X = train_df[feature_cols].copy()
y = train_df["Target"].copy()
X_test = test_df[feature_cols].copy()

X_train, X_valid, y_train, y_valid = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

used_catboost = False
catboost_error = None

try:
    from catboost import CatBoostClassifier

    model = CatBoostClassifier(
        loss_function="MultiClass",
        eval_metric="TotalF1",
        iterations=1200,
        learning_rate=0.05,
        depth=8,
        random_seed=42,
        verbose=200,
    )
    model.fit(X_train, y_train, eval_set=(X_valid, y_valid), use_best_model=True)
    used_catboost = True
except Exception as e:
    from sklearn.ensemble import RandomForestClassifier

    classes = np.unique(y_train)
    class_weights = compute_class_weight(
        class_weight="balanced", classes=classes, y=y_train
    )
    class_weight_dict = {cls: w for cls, w in zip(classes, class_weights)}

    model = RandomForestClassifier(
        n_estimators=600,
        random_state=42,
        n_jobs=-1,
        min_samples_leaf=2,
        class_weight=class_weight_dict,
    )
    model.fit(X_train, y_train)
    catboost_error = type(e).__name__

valid_pred = model.predict(X_valid)
print("Validation Macro-F1:", round(f1_score(y_valid, valid_pred, average="macro"), 4))
print("Validation Accuracy:", round(accuracy_score(y_valid, valid_pred), 4))
print(classification_report(y_valid, valid_pred))

if used_catboost:
    from catboost import CatBoostClassifier

    best_iter = model.get_best_iteration()
    if best_iter is None or best_iter <= 0:
        best_iter = 800

    final_model = CatBoostClassifier(
        loss_function="MultiClass",
        eval_metric="TotalF1",
        iterations=int(best_iter),
        learning_rate=0.05,
        depth=8,
        random_seed=42,
        verbose=False,
    )
    print(f"Using CatBoost with iterations={int(best_iter)}")
else:
    from sklearn.ensemble import RandomForestClassifier

    final_model = RandomForestClassifier(
        n_estimators=600,
        random_state=42,
        n_jobs=-1,
        min_samples_leaf=2,
        class_weight=model.get_params()["class_weight"],
    )
    print(f"Using RandomForest fallback because CatBoost was unavailable ({catboost_error})")

final_model.fit(X, y)
test_pred = final_model.predict(X_test)
test_pred = np.asarray(test_pred).reshape(-1)

submission = pd.DataFrame({
    "id": test_df["id"],
    "Target": test_pred,
})
submission.to_csv("submission.csv", index=False)

print("Saved submission.csv")
print("submission shape:", submission.shape)
display(submission.head())

Validation Macro-F1: 0.7917
Validation Accuracy: 0.8265
              precision    recall  f1-score   support

     Dropout       0.91      0.82      0.86      5059
    Enrolled       0.62      0.64      0.63      2988
    Graduate       0.86      0.91      0.88      7257

    accuracy                           0.83     15304
   macro avg       0.80      0.79      0.79     15304
weighted avg       0.83      0.83      0.83     15304

Using RandomForest fallback because CatBoost was unavailable (ModuleNotFoundError)
Saved submission.csv
submission shape: (51012, 2)

      id    Target
0  76518   Dropout
1  76519  Graduate
2  76520  Graduate
3  76521  Enrolled
4  76522  Enrolled

In [8]:
# Advanced model search + ensemble to try beating baseline
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score, accuracy_score, classification_report
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier, HistGradientBoostingClassifier
from sklearn.utils.class_weight import compute_class_weight
import numpy as np
import pandas as pd

train_df = pd.read_csv("train_assignment.csv")
test_df = pd.read_csv("test_assignment.csv")

feature_cols = [c for c in train_df.columns if c not in ["Target", "id"]]
X = train_df[feature_cols].copy()
X_test = test_df[feature_cols].copy()
y_raw = train_df["Target"].copy()

le = LabelEncoder()
y = le.fit_transform(y_raw)
class_names = le.classes_

X_train, X_valid, y_train, y_valid = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

classes = np.unique(y_train)
class_weights = compute_class_weight(class_weight="balanced", classes=classes, y=y_train)
class_weight_dict = {cls: w for cls, w in zip(classes, class_weights)}
sample_weight_train = np.array([class_weight_dict[v] for v in y_train])

models = {
    "rf": RandomForestClassifier(
        n_estimators=900,
        random_state=42,
        n_jobs=-1,
        max_features="sqrt",
        min_samples_leaf=1,
        class_weight=class_weight_dict,
    ),
    "et": ExtraTreesClassifier(
        n_estimators=1200,
        random_state=42,
        n_jobs=-1,
        max_features="sqrt",
        min_samples_leaf=1,
        class_weight=class_weight_dict,
    ),
    "hgb": HistGradientBoostingClassifier(
        learning_rate=0.05,
        max_depth=10,
        max_iter=500,
        min_samples_leaf=20,
        l2_regularization=0.1,
        random_state=42,
        early_stopping=True,
        validation_fraction=0.1,
    ),
}

# Optional XGBoost if available
try:
    from xgboost import XGBClassifier

    models["xgb"] = XGBClassifier(
        objective="multi:softprob",
        num_class=len(class_names),
        n_estimators=900,
        learning_rate=0.04,
        max_depth=8,
        subsample=0.9,
        colsample_bytree=0.9,
        reg_lambda=1.5,
        random_state=42,
        n_jobs=-1,
        eval_metric="mlogloss",
    )
    print("XGBoost available and included.")
except Exception as e:
    print(f"XGBoost not available: {type(e).__name__}")

val_probas = {}
model_scores = []

for name, model in models.items():
    print(f"\nTraining: {name}")
    if name == "hgb":
        model.fit(X_train, y_train, sample_weight=sample_weight_train)
    else:
        model.fit(X_train, y_train)

    prob = model.predict_proba(X_valid)
    pred = np.argmax(prob, axis=1)

    macro_f1 = f1_score(y_valid, pred, average="macro")
    acc = accuracy_score(y_valid, pred)
    blend_score = 0.7 * macro_f1 + 0.3 * acc

    val_probas[name] = prob
    model_scores.append((name, macro_f1, acc, blend_score))
    print(f"{name} -> Macro-F1: {macro_f1:.5f} | Accuracy: {acc:.5f} | Blend: {blend_score:.5f}")

score_df = pd.DataFrame(model_scores, columns=["model", "macro_f1", "accuracy", "blend"]).sort_values(
    by="blend", ascending=False
).reset_index(drop=True)

print("\nValidation leaderboard:")
display(score_df)

# Build weighted soft-voting using top 3 models (or fewer if fewer available)
top_k = min(3, len(score_df))
top_models = score_df.head(top_k).copy()
weights = (top_models["blend"] ** 4).to_numpy()
weights = weights / weights.sum()

ensemble_prob = np.zeros_like(next(iter(val_probas.values())))
for w, name in zip(weights, top_models["model"].tolist()):
    ensemble_prob += w * val_probas[name]

ensemble_pred = np.argmax(ensemble_prob, axis=1)
ensemble_macro_f1 = f1_score(y_valid, ensemble_pred, average="macro")
ensemble_acc = accuracy_score(y_valid, ensemble_pred)
ensemble_blend = 0.7 * ensemble_macro_f1 + 0.3 * ensemble_acc

print("\nEnsemble (top-weighted soft vote) -> ",
      f"Macro-F1: {ensemble_macro_f1:.5f} | Accuracy: {ensemble_acc:.5f} | Blend: {ensemble_blend:.5f}")

best_single = score_df.iloc[0]
use_ensemble = ensemble_blend >= float(best_single["blend"])

if use_ensemble:
    print("Using ENSEMBLE for final training.")
    selected_model_names = top_models["model"].tolist()
else:
    print(f"Using BEST SINGLE model for final training: {best_single['model']}")
    selected_model_names = [best_single["model"]]

# Refit chosen model(s) on full training data and predict test
trained_full_models = {}
for name in selected_model_names:
    m = models[name]
    if name == "hgb":
        sample_weight_full = np.array([class_weight_dict[v] for v in y])
        m.fit(X, y, sample_weight=sample_weight_full)
    else:
        m.fit(X, y)
    trained_full_models[name] = m

if len(trained_full_models) == 1:
    only_model = next(iter(trained_full_models.values()))
    test_prob = only_model.predict_proba(X_test)
else:
    selected_scores = score_df.set_index("model").loc[selected_model_names, "blend"].to_numpy()
    selected_weights = (selected_scores ** 4) / np.sum(selected_scores ** 4)
    test_prob = np.zeros((len(X_test), len(class_names)), dtype=float)
    for w, name in zip(selected_weights, selected_model_names):
        test_prob += w * trained_full_models[name].predict_proba(X_test)

test_pred_idx = np.argmax(test_prob, axis=1)
test_pred = le.inverse_transform(test_pred_idx)

submission = pd.DataFrame({
    "id": test_df["id"],
    "Target": test_pred,
})
submission.to_csv("submission.csv", index=False)

print("\nSaved improved submission.csv")
print("submission shape:", submission.shape)
print("Target distribution in prediction:")
display(submission["Target"].value_counts(normalize=True).rename("pct"))
display(submission.head())

# Optional: inspect confusion metrics for the selected validation output
print("\nValidation report (selected strategy):")
if use_ensemble:
    print(classification_report(y_valid, ensemble_pred, target_names=class_names))
else:
    best_name = selected_model_names[0]
    best_pred = np.argmax(val_probas[best_name], axis=1)
    print(classification_report(y_valid, best_pred, target_names=class_names))

XGBoost available and included.

Training: rf
rf -> Macro-F1: 0.78296 | Accuracy: 0.82403 | Blend: 0.79528

Training: et
et -> Macro-F1: 0.78145 | Accuracy: 0.82292 | Blend: 0.79389

Training: hgb
hgb -> Macro-F1: 0.79110 | Accuracy: 0.81554 | Blend: 0.79843

Training: xgb
xgb -> Macro-F1: 0.79312 | Accuracy: 0.83089 | Blend: 0.80445

Validation leaderboard:

  model  macro_f1  accuracy     blend
0   xgb  0.793123  0.830894  0.804454
1   hgb  0.791103  0.815538  0.798434
2    rf  0.782955  0.824033  0.795279
3    et  0.781453  0.822922  0.793894

Ensemble (top-weighted soft vote) ->  Macro-F1: 0.79715 | Accuracy: 0.82965 | Blend: 0.80690
Using ENSEMBLE for final training.

Saved improved submission.csv
submission shape: (51012, 2)
Target distribution in prediction:

Target
Graduate    0.501392
Dropout     0.294127
Enrolled    0.204481
Name: pct, dtype: float64

      id    Target
0  76518   Dropout
1  76519  Graduate
2  76520  Graduate
3  76521  Enrolled
4  76522  Enrolled

Validation report (selected strategy):
              precision    recall  f1-score   support

     Dropout       0.91      0.83      0.87      5059
    Enrolled       0.63      0.66      0.64      2988
    Graduate       0.87      0.90      0.88      7257

    accuracy                           0.83     15304
   macro avg       0.80      0.80      0.80     15304
weighted avg       0.83      0.83      0.83     15304

In [10]:
# Upgraded preprocessing + multi-ensemble selection (designed to reduce overfitting)
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import f1_score, accuracy_score, classification_report
from sklearn.preprocessing import LabelEncoder, RobustScaler
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier, HistGradientBoostingClassifier
from sklearn.utils.class_weight import compute_class_weight
import numpy as np
import pandas as pd

RANDOM_STATE = 42
N_SPLITS = 5

train_df = pd.read_csv("train_assignment.csv")
test_df = pd.read_csv("test_assignment.csv")

def add_features(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()

    # Core academic aggregates
    df["cu_total_enrolled"] = df["cu1_enrolled"] + df["cu2_enrolled"]
    df["cu_total_evaluations"] = df["cu1_evaluations"] + df["cu2_evaluations"]
    df["cu_total_approved"] = df["cu1_approved"] + df["cu2_approved"]
    df["cu_total_credited"] = df["cu1_credited"] + df["cu2_credited"]
    df["cu_total_without_eval"] = df["cu1_without_evaluations"] + df["cu2_without_evaluations"]

    # Smoothed ratios reduce instability for low-count students
    df["cu1_approval_rate_enrolled"] = (df["cu1_approved"] + 1.0) / (df["cu1_enrolled"] + 2.0)
    df["cu2_approval_rate_enrolled"] = (df["cu2_approved"] + 1.0) / (df["cu2_enrolled"] + 2.0)
    df["cu1_approval_rate_eval"] = (df["cu1_approved"] + 1.0) / (df["cu1_evaluations"] + 2.0)
    df["cu2_approval_rate_eval"] = (df["cu2_approved"] + 1.0) / (df["cu2_evaluations"] + 2.0)
    df["cu_total_approval_rate_enrolled"] = (df["cu_total_approved"] + 1.0) / (df["cu_total_enrolled"] + 2.0)
    df["cu_total_approval_rate_eval"] = (df["cu_total_approved"] + 1.0) / (df["cu_total_evaluations"] + 2.0)

    # Grade signals
    df["cu_grade_mean"] = (df["cu1_grade"] + df["cu2_grade"]) / 2.0
    df["cu_grade_gap"] = df["cu1_grade"] - df["cu2_grade"]

    # Risk / engagement interactions
    df["financial_risk"] = df["debtor_flag"] * (1 - df["tuition_up_to_date_flag"])
    df["engagement_gap"] = df["cu_total_evaluations"] - df["cu_total_approved"]
    df["approved_per_age"] = (df["cu_total_approved"] + 1.0) / (df["age_at_enrollment"] + 1.0)

    return df

train_fe = add_features(train_df)
test_fe = add_features(test_df)

target_col = "Target"
id_col = "id"
feature_cols = [c for c in train_fe.columns if c not in [target_col, id_col]]

X_all = train_fe[feature_cols].copy()
X_test_all = test_fe[feature_cols].copy()

le = LabelEncoder()
y_all = le.fit_transform(train_fe[target_col])
class_names = le.classes_
n_classes = len(class_names)

classes = np.unique(y_all)
cw_values = compute_class_weight(class_weight="balanced", classes=classes, y=y_all)
class_weight_dict = {cls: w for cls, w in zip(classes, cw_values)}

def get_models():
    models = {
        "xgb": None,
        "hgb": HistGradientBoostingClassifier(
            learning_rate=0.04,
            max_depth=8,
            max_iter=700,
            min_samples_leaf=40,
            l2_regularization=1.0,
            random_state=RANDOM_STATE,
            early_stopping=True,
            validation_fraction=0.1,
        ),
        "rf": RandomForestClassifier(
            n_estimators=1200,
            random_state=RANDOM_STATE,
            n_jobs=-1,
            max_features="sqrt",
            min_samples_leaf=3,
            class_weight=class_weight_dict,
        ),
        "et": ExtraTreesClassifier(
            n_estimators=1500,
            random_state=RANDOM_STATE,
            n_jobs=-1,
            max_features="sqrt",
            min_samples_leaf=2,
            class_weight=class_weight_dict,
        ),
        "lr": make_pipeline(
            RobustScaler(),
            LogisticRegression(
                C=0.7,
                class_weight="balanced",
                max_iter=2500,
                multi_class="multinomial",
                random_state=RANDOM_STATE,
            ),
        ),
    }

    try:
        from xgboost import XGBClassifier
        models["xgb"] = XGBClassifier(
            objective="multi:softprob",
            num_class=n_classes,
            n_estimators=3000,
            learning_rate=0.025,
            max_depth=6,
            min_child_weight=6,
            subsample=0.85,
            colsample_bytree=0.8,
            reg_lambda=3.0,
            reg_alpha=0.3,
            gamma=0.5,
            random_state=RANDOM_STATE,
            n_jobs=-1,
            eval_metric="mlogloss",
            tree_method="hist",
        )
    except Exception:
        pass

    # Drop models that are unavailable
    models = {k: v for k, v in models.items() if v is not None}
    return models

def fit_clip_bounds(X_tr: pd.DataFrame, q_low=0.005, q_high=0.995):
    lo = X_tr.quantile(q_low)
    hi = X_tr.quantile(q_high)
    return lo, hi

def apply_clip(X_df: pd.DataFrame, lo: pd.Series, hi: pd.Series) -> pd.DataFrame:
    return X_df.clip(lower=lo, upper=hi, axis=1)

skf = StratifiedKFold(n_splits=N_SPLITS, shuffle=True, random_state=RANDOM_STATE)
base_models = get_models()
model_names = list(base_models.keys())

print("Models used:", model_names)

oof_probas = {name: np.zeros((len(X_all), n_classes), dtype=float) for name in model_names}
test_fold_probas = {name: [] for name in model_names}

for fold, (tr_idx, va_idx) in enumerate(skf.split(X_all, y_all), start=1):
    X_tr = X_all.iloc[tr_idx].copy()
    X_va = X_all.iloc[va_idx].copy()
    y_tr = y_all[tr_idx]
    y_va = y_all[va_idx]

    # Fold-wise clipping to reduce tail noise without leaking validation labels
    lo, hi = fit_clip_bounds(X_tr)
    X_tr = apply_clip(X_tr, lo, hi)
    X_va = apply_clip(X_va, lo, hi)
    X_te_fold = apply_clip(X_test_all, lo, hi)

    sw_tr = np.array([class_weight_dict[v] for v in y_tr])

    print(f"\nFold {fold}/{N_SPLITS}")
    fold_models = get_models()
    for name in model_names:
        model = fold_models[name]

        if name == "xgb":
            model.fit(
                X_tr, y_tr,
                eval_set=[(X_va, y_va)],
                verbose=False,
            )
        elif name == "hgb":
            model.fit(X_tr, y_tr, sample_weight=sw_tr)
        elif name == "lr":
            model.fit(X_tr, y_tr, logisticregression__sample_weight=sw_tr)
        else:
            model.fit(X_tr, y_tr)

        va_prob = model.predict_proba(X_va)
        te_prob = model.predict_proba(X_te_fold)

        oof_probas[name][va_idx] = va_prob
        test_fold_probas[name].append(te_prob)

# Per-model OOF scores
rows = []
test_probas_mean = {}
for name in model_names:
    oof_pred = np.argmax(oof_probas[name], axis=1)
    macro_f1 = f1_score(y_all, oof_pred, average="macro")
    acc = accuracy_score(y_all, oof_pred)
    blend = 0.75 * macro_f1 + 0.25 * acc
    rows.append((name, macro_f1, acc, blend))
    test_probas_mean[name] = np.mean(np.stack(test_fold_probas[name], axis=0), axis=0)

score_df = pd.DataFrame(rows, columns=["model", "macro_f1", "accuracy", "blend"]).sort_values(
    by="blend", ascending=False
).reset_index(drop=True)

print("\nOOF leaderboard (anti-overfit estimate):")
display(score_df)

# Ensemble A: weighted soft vote of top models
top_k = min(4, len(score_df))
top = score_df.head(top_k).copy()
w = (top["blend"].to_numpy() ** 6)
w = w / w.sum()

oof_soft = np.zeros((len(X_all), n_classes), dtype=float)
test_soft = np.zeros((len(X_test_all), n_classes), dtype=float)

for weight, name in zip(w, top["model"].tolist()):
    oof_soft += weight * oof_probas[name]
    test_soft += weight * test_probas_mean[name]

pred_soft = np.argmax(oof_soft, axis=1)
f1_soft = f1_score(y_all, pred_soft, average="macro")
acc_soft = accuracy_score(y_all, pred_soft)
blend_soft = 0.75 * f1_soft + 0.25 * acc

# Ensemble B: stacking on OOF probabilities
stack_X = np.hstack([oof_probas[name] for name in model_names])
stack_X_test = np.hstack([test_probas_mean[name] for name in model_names])

meta = LogisticRegression(
    C=0.5,
    max_iter=3000,
    multi_class="multinomial",
    class_weight="balanced",
    random_state=RANDOM_STATE,
    solver="lbfgs",
)
meta.fit(stack_X, y_all)

oof_stack_prob = meta.predict_proba(stack_X)
pred_stack = np.argmax(oof_stack_prob, axis=1)
f1_stack = f1_score(y_all, pred_stack, average="macro")
acc_stack = accuracy_score(y_all, pred_stack)
blend_stack = 0.75 * f1_stack + 0.25 * acc_stack

print("\nEnsemble comparison:")
print(f"SoftVote  -> Macro-F1: {f1_soft:.5f} | Accuracy: {acc_soft:.5f} | Blend: {blend_soft:.5f}")
print(f"Stacking  -> Macro-F1: {f1_stack:.5f} | Accuracy: {acc_stack:.5f} | Blend: {blend_stack:.5f}")

if blend_stack >= blend_soft:
    chosen = "stacking"
    final_test_prob = meta.predict_proba(stack_X_test)
    final_oof_pred = pred_stack
else:
    chosen = "soft_vote"
    final_test_prob = test_soft
    final_oof_pred = pred_soft

final_test_pred_idx = np.argmax(final_test_prob, axis=1)
final_test_pred = le.inverse_transform(final_test_pred_idx)

submission = pd.DataFrame({
    "id": test_df["id"],
    "Target": final_test_pred,
})
submission.to_csv("submission.csv", index=False)

print(f"\nChosen final ensemble: {chosen}")
print("Saved upgraded submission.csv")
print("submission shape:", submission.shape)
print("Predicted target distribution:")
display(submission["Target"].value_counts(normalize=True).rename("pct"))

print("\nOOF classification report for selected strategy:")
print(classification_report(y_all, final_oof_pred, target_names=class_names))

display(submission.head())

Models used: ['xgb', 'hgb', 'rf', 'et', 'lr']

Fold 1/5

/opt/homebrew/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

Fold 2/5

/opt/homebrew/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

Fold 3/5

/opt/homebrew/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

Fold 4/5

/opt/homebrew/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

Fold 5/5

/opt/homebrew/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

OOF leaderboard (anti-overfit estimate):

  model  macro_f1  accuracy     blend
0   xgb  0.794149  0.831373  0.803455
1   hgb  0.793077  0.817337  0.799142
2    et  0.790336  0.822251  0.798314
3    rf  0.789038  0.822251  0.797341
4    lr  0.743335  0.753953  0.745989

/opt/homebrew/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

Ensemble comparison:
SoftVote  -> Macro-F1: 0.79803 | Accuracy: 0.82892 | Blend: 0.78701
Stacking  -> Macro-F1: 0.79602 | Accuracy: 0.82090 | Blend: 0.80224

Chosen final ensemble: stacking
Saved upgraded submission.csv
submission shape: (51012, 2)
Predicted target distribution:

Target
Graduate    0.460794
Dropout     0.289108
Enrolled    0.250098
Name: pct, dtype: float64

OOF classification report for selected strategy:
              precision    recall  f1-score   support

     Dropout       0.91      0.82      0.86     25296
    Enrolled       0.58      0.75      0.65     14940
    Graduate       0.90      0.86      0.88     36282

    accuracy                           0.82     76518
   macro avg       0.80      0.81      0.80     76518
weighted avg       0.84      0.82      0.83     76518

      id    Target
0  76518   Dropout
1  76519  Graduate
2  76520  Graduate
3  76521  Enrolled
4  76522  Enrolled

In [11]:
# Fix ensemble selection bug (use the correct accuracy term for soft vote)
required_vars = [
    "f1_soft", "acc_soft", "f1_stack", "acc_stack",
    "test_soft", "stack_X_test", "meta", "le", "test_df"
]

missing_vars = [v for v in required_vars if v not in globals()]
if missing_vars:
    raise RuntimeError(f"Run Cell 7 first. Missing variables: {missing_vars}")

blend_soft_correct = 0.75 * f1_soft + 0.25 * acc_soft
blend_stack_correct = 0.75 * f1_stack + 0.25 * acc_stack

print("Corrected ensemble comparison:")
print(f"SoftVote  -> Macro-F1: {f1_soft:.5f} | Accuracy: {acc_soft:.5f} | Blend: {blend_soft_correct:.5f}")
print(f"Stacking  -> Macro-F1: {f1_stack:.5f} | Accuracy: {acc_stack:.5f} | Blend: {blend_stack_correct:.5f}")

if blend_soft_correct >= blend_stack_correct:
    chosen_corrected = "soft_vote"
    final_test_prob_corrected = test_soft
else:
    chosen_corrected = "stacking"
    final_test_prob_corrected = meta.predict_proba(stack_X_test)

final_test_pred_idx_corrected = np.argmax(final_test_prob_corrected, axis=1)
final_test_pred_corrected = le.inverse_transform(final_test_pred_idx_corrected)

submission = pd.DataFrame({
    "id": test_df["id"],
    "Target": final_test_pred_corrected,
})
submission.to_csv("submission.csv", index=False)

print(f"\nChosen final ensemble (corrected): {chosen_corrected}")
print("Saved corrected submission.csv")
print("submission shape:", submission.shape)
display(submission.head())

Corrected ensemble comparison:
SoftVote  -> Macro-F1: 0.79803 | Accuracy: 0.82892 | Blend: 0.80575
Stacking  -> Macro-F1: 0.79602 | Accuracy: 0.82090 | Blend: 0.80224

Chosen final ensemble (corrected): soft_vote
Saved corrected submission.csv
submission shape: (51012, 2)

      id    Target
0  76518   Dropout
1  76519  Graduate
2  76520  Graduate
3  76521  Enrolled
4  76522  Enrolled